kind: Pod
apiVersion: v1
metadata:
  name: environment
spec:
  containers:
  - name: c00
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo Hello Safwan; sleep 5; done"]
    env:
    - name: MYNAME
      value: SAFWAN
