apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-second-app
  namespace: argocd   # ArgoCD always watches its own namespace
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/<your-repo>.git
    targetRevision: main     # branch, tag, or commit
    path: manifests/app2     # folder inside repo containing k8s YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: app2-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
